---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by enki.
--- DateTime: 4/14/24 3:01 PM
---

-- GameStateRegistry.lua
local GameStateRegistry = {}

-- Define MainMenuState
GameStateRegistry.MainMenuState = {
    enter = function()
        print("[INFO] Entering MainMenuState")
    end,
    exit = function()
        print("Exiting MainMenuState")
    end,
    update = function(deltaTime)
        -- Update logic here
    end,
    render = function()
        -- Rendering logic here
    end
}

-- Define GameplayState
GameStateRegistry.GameplayState = {
    enter = function()
        print("[INFO] Entering GameplayState 1")
    end,
    exit = function()
        print("Exiting GameplayState")
        stopAllActiveAudioEvents()
    end,
    update = function(deltaTime)
        -- Update logic here
    end,
    render = function()
        -- Rendering logic here
    end
}

-- Return the registry containing all game states
return GameStateRegistry
