---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by enki.
--- DateTime: 3/28/24 10:27 PM
---


-- Function to create and setup a new entity
function createAndSetupEntity()
    -- Create a new entity
    local newEntity = createEntity()
    logMessage("[INFO] Lua created Entity: " .. newEntity);

    -- Attach components to the entity
    attachComponent(newEntity, ComponentTypes.Transform)
    attachComponent(newEntity, ComponentTypes.Renderable)
    attachComponent(newEntity, ComponentTypes.Sprite)
    attachComponent(newEntity, ComponentTypes.Texture)

    -- Set sprite, texture, render layer, and initial transform
    setSprite(newEntity, 0, 0, 100, 720)
    setTexture(newEntity, "../Game/Assets/background_DarkPath_Ritual_Scene.png")
    setRenderLayer(newEntity, RenderLayer.background)
    setTransform(newEntity, 0, 0)
end

-- constructLevel is called from Core. All level design should go in constructLevel so hot reloading the Lua script
-- updates all entities
function constructLevel()
    -- Call the function to create and setup the entity

    createAndSetupEntity()
end


