---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by enki.
--- DateTime: 3/28/24 10:27 PM
---


MainMenuState = {}

function MainMenuState.enter()
    print("[INFO] Entering MainMenuState")
end

function MainMenuState.exit()
    print("Exiting MainMenuState")
end

function MainMenuState.update(deltaTime)
    -- Update logic here
end

function MainMenuState.render()
    -- Rendering logic here
end

GameplayState = {}

function GameplayState.enter()
    print("[INFO] Entering GameplayState")
end

function GameplayState.exit()
    print("Exiting GameplayStateState")
end

function GameplayState.update(deltaTime)
    -- Update logic here
end

function GameplayState.render()
    -- Rendering logic here
end

-- Register the state with a global or a specific Lua registry for states
-- This ensures GameStateRegistry is created if it doesn't exist
GameStateRegistry = GameStateRegistry or {}
GameStateRegistry["MainMenuState"] = MainMenuState

GameStateRegistry = GameStateRegistry or {}
GameStateRegistry["GameplayState"] = GameplayState




-- Function to create and setup a new entity
function createAndSetupEntity()
    -- Create a new entity
    local newEntity = createEntity()
    logMessage("[INFO] Lua created Entity: " .. newEntity);

    -- Attach components to the entity
    attachComponent(newEntity, ComponentTypes.Transform)
    attachComponent(newEntity, ComponentTypes.Renderable)
    attachComponent(newEntity, ComponentTypes.Sprite)
    attachComponent(newEntity, ComponentTypes.Texture)

    -- Set sprite, texture, render layer, and initial transform
    setSprite(newEntity, 0, 0, 900, 720)
    setTexture(newEntity, "../Game/Assets/background_DarkPath_Ritual_Scene.png")
    setRenderLayer(newEntity, RenderLayer.background)
    setTransform(newEntity, 0, 0)
end





-- constructLevel is called from Core. All level design should go in constructLevel so hot reloading the Lua script
-- updates all entities
function constructLevel()
    -- Call the function to create and setup the entity

    createAndSetupEntity()
end


